name: Deploy to GitHub Pages

on: 
  push:
    branches: [ deploy-to-gh-pages ]

permissions:
  contents: read  
  pages: write      
  id-token: write   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: |
          echo "VITE_APP_EMAILJS_SERVICE_ID=${{ secrets.VITE_APP_EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_APP_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_APP_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_APP_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_APP_EMAILJS_PUBLIC_KEY }}" >> .env
          npm run build  
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3   
        with:
           name: 'github-pages'
           path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'